posts/routes.py
from flask import render_template, request, Flask, redirect, Blueprint, url_for, flash, session
from app_config import db, bcrypt
from flask_login import login_required, current_user, login_user, logout_user
from models import User, Post
from datetime import datetime
import cloudinary
import cloudinary.uploader
from werkzeug.utils import secure_filename



posts = Blueprint('posts', __name__)


cloudinary.config(
    cloud_name = "duyoxldib",
    api_key = "778871683257166",
  api_secret = "NM2WHVuvMytyfnVziuzRScXrrNk"
)

app = Flask(__name__)
app.secret_key = "wrweerrhttjytjtdjydtytytytdytdhghmftytdmtty,mtdmyty,mytftdjrtereyrsjtrjmtdy"

app.config['UPLOADED_PHOTOS_DEST'] = 'static/assets/img'



@posts.route('/new_post', methods=['GET', 'POST'])
@login_required
def new_post():
    if not current_user.admin:
        return redirect(url_for('main.index'))
    
    if request.method == 'POST':
        title = request.form.get('title')
        category = request.form.get('category')
        content = request.form.get('ckeditor')
        date_posted = datetime.now()
        image = request.files.get('image')
        user_id = current_user.id

        if image:
            filename = secure_filename(image.filename)
            response = cloudinary.uploader.upload(image, public_id=f"posts/{filename}")
            image = response['secure_url']
        
        post = Post(title=title, category=category, content=content, date_posted=date_posted, image=image, user_id=user_id)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('new_post.html')





# View post
@posts.route('/post_details/<int:post_id>', methods=['GET', 'POST'])
def post_details(post_id):
    post = Post.query.get_or_404(post_id)

    all_posts = Post.query.order_by(Post.date_posted.desc()).all()

    
    latest_fashion_post = next((p for p in all_posts if p.category == 'Fashion and Beauty'), None)
    latest_tech = next((p for p in all_posts if p.category == 'Technology'), None)
    latest_sports = next((p for p in all_posts if p.category == 'Sports'), None)
    latest_crime = next((p for p in all_posts if p.category == 'Crime'), None)
    latest_sex_relationship = next((p for p in all_posts if p.category == 'Sex and Relationship'), None)
    latest_entertainment = next((p for p in all_posts if p.category == 'Entertainment'), None)

    # Recent posts limit to 4
    recent_posts = Post.query.order_by(Post.date_posted.desc()).limit(10).all()
    return render_template('post_details.html', post=post, recent_posts=recent_posts, latest_fashion_post=latest_fashion_post, latest_tech=latest_tech, latest_sports=latest_sports, latest_crime=latest_crime, latest_sex_relationship=latest_sex_relationship, latest_entertainment=latest_entertainment)

templates/new_post.html
{% extends "layout.html" %}
{% block content %}

{{ ckeditor.load() }}
<!-- Create Post -->
<br>
<div class="container mb-5 p-5 " style="width: 40%;">
    <h1>Create Post</h1>
    <form action="{{ url_for('posts.new_post') }}" method="post" enctype="multipart/form-data" >
        <div class="form-group mb-3">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="Enter Title" required>
        </div>
        <div class="form-group mb-3 ">
            <label for="category">Category</label>
            <select class="form-select" id="category" name="category" aria-label="Default select example" required>
                <option selected>Please pick a category</option>
                <option value="Sports">Sports</option>
                <option value="Entertainment">Entertainment</option>
                <option value="Health">Health</option>
                <option value="Technology">Technology</option>
                <option value="Science">Science</option>
                <option value="Business">Business</option>
                <option value="Sex and Relationship">Sex and Relationship</option>
                <option value="Crime">Crime</option>
                <option value="Politics">Politics</option>
                <option value="Religion">Religion</option>
                <option value="Education and Career">Education and Career</option>
                <option value="Fashion and Beauty">Fashion and Beauty</option>
            </select>
        </div>
        <div class="form-group mb-3">
            <label for="content">Content</label>
            {{ ckeditor.create() }}
            <!-- <textarea class="form-control" id="content" name="content" rows="3" placeholder="Enter Content" required></textarea> -->
        </div>
        <div class="form-group mb-3">
            <!-- <label for="image">Image</label> -->
            <input type="file" id="image" name="image" accept="image/*" >
            <img {% if current_user.profile_picture %} src="{{ current_user.profile_pic }}" {% else %}
            src="{{ url_for('static', filename='/assets/img/default.png') }}" {% endif %} alt="image"
            class=" article-img profile_pic mt-3 border d-flex justify-content-center" id="display_picture"
            style="width: 300px; height: 150px; border-radius: 10px; cursor: pointer; ">
        </div>
        <button type="submit" class="btn btn-primary">Create Post</button>
    </form>
</div>
<script>
    // JavaScript
    profile_icon = document.getElementById("display_picture");
    profile_upload = document.getElementById("image");
    profile_icon.addEventListener("click", function () {
        profile_upload.click();
    });
    profile_upload.addEventListener("change", function () {
        const selectedFile = this.files[0];
        if (selectedFile) {
            // Update the src attribute of the image element with the URL of the selected file
            profile_icon.src = URL.createObjectURL(selectedFile);
        }
    });
</script>
{% endblock %}